export { inspect, type InspectOptions } from "./inspect.js";
export { extractProtectedSpans } from "./protected/extract.js";
export { validateCandidate, type GatePolicy } from "./gates/policy.js";
export { diff, type ContentDiff, type DiffSegment } from "./diff/diff.js";
export { previewSafeFixes, type FixPreview, type FixPreviewOptions } from "./fixes/preview.js";
export { detectC2paTextCredentials, variationSelectorToByte, isCredentialCarrier, withinCredential, credentialNotice, type C2paTextCredential } from "./provenance/c2pa-text.js";
export { buildReceipt, verifyReceipt, type ReceiptInput } from "./receipts/build.js";
export { registerPatternPack, type PatternPack } from "./patterns/en-gb-v1.js";
export { listMethods, type MethodDescriptor } from "./capabilities.js";
export { projectVisibleText, type VisibleTextProjection, type SourceMapRun } from "./source/visible-text.js";
export { inspectUnicode, UNICODE_RULES_VERSION, type UnicodeFinding } from "./unicode/inspect.js";
export { inspectSignalsV2, computeEditorialSignals, EN_SIGNALS_PATTERN_VERSION, type EditorialSignalsResult, type SignalsClassification } from "./patterns/en-signals-v2.js";
export { prefixedSha256, sha256Hex, utf8Bytes } from "./source/utf8.js";
export { computeCombinedVerdict, assertAxisIndependence, COMBINED_VERDICT_VERSION, type CombinedVerdictInput, type CombinedVerdictResult, type CombinedEvidenceItem, type EvidenceTier, type WatermarkOutcome, type ModelReading, type IntegrityFinding, type AiReading, type IntegrityStatus, type SuggestionLevel, type ConfidenceBand } from "./verdict/combine.js";
export { CHECKER_RESULT_RUNTIME_VERSION, CYCLE5_MODEL_IDENTITY, CHECKER_SCORE_SCALE, CHECKER_HONESTY_LINE, CHECKER_LEVELS, levelForCycle5Score, formatCheckerScoreTexts, presentCycle5Result, notAssessedAiPattern, composeCheckerAxes, buildContentFreeSharePayload, assertCheckerResultInvariants, type CheckerLevelId, type Cycle5BandId, type CheckerEvidenceInput, type Cycle5SectionInput, type Cycle5PresentationInput, type PresentedCycle5Section, type PresentedCycle5Result, type SharePayloadInput } from "./report/checker-result.js";
