import type { AnalysisRequest, AnalysisResult, MethodResult } from "@opace/content-integrity-contracts";
import { projectVisibleText } from "./source/visible-text.js";
import { prefixedSha256 } from "./source/utf8.js";
import { inspectUnicode, UNICODE_RULES_VERSION } from "./unicode/inspect.js";
import { extractProtectedSpans } from "./protected/extract.js";
import { inspectPatterns, runRegisteredPacks } from "./patterns/en-gb-v1.js";
import { computeEditorialSignals, EN_SIGNALS_PATTERN_VERSION } from "./patterns/en-signals-v2.js";
import { computeCombinedVerdict, type WatermarkOutcome } from "./verdict/combine.js";

export interface InspectOptions {now?:()=>string;analysisId?:()=>string;onProgress?:(phase:"validating"|"mapping_text"|"unicode_checks"|"protected_spans"|"writing_patterns"|"complete")=>void;signal?:AbortSignal}
const limits=(message:string):[string,...string[]]=>[message,"Authorship cannot be proved from this check."];
const WRITING_SIGNAL_RULES_RUN=116; // 3 en-gb-v1 rules + 113 weighted signal categories (v2 51 + v3 55 + v4 rhythm 7)
export async function inspect(request:AnalysisRequest,options:InspectOptions={}):Promise<AnalysisResult>{
  const now=options.now??(()=>new Date().toISOString()),started=now();const progress=(p:Parameters<NonNullable<InspectOptions["onProgress"]>>[0])=>{if(options.signal?.aborted)throw new DOMException("Inspection cancelled","AbortError");options.onProgress?.(p);};
  progress("validating");if(request.schema_version!=="1.0"||!request.contract_version.startsWith("1."))throw new Error("contract_incompatible");if(request.source.content.length>250000)throw new Error("request_too_large");if(hasUnpairedSurrogate(request.source.content))throw new Error("invalid_unicode_unpaired_surrogate");
  const sourceHash=prefixedSha256(request.source.content);progress("mapping_text");const projection=projectVisibleText(request.source.content,request.source.content_type);progress("unicode_checks");const unicode=inspectUnicode(request.source.content);progress("protected_spans");const protectedSpans=extractProtectedSpans({...request.source,content_hash:sourceHash});progress("writing_patterns");const patternFindings=[...inspectPatterns(projection.text),...runRegisteredPacks(projection.text)];const editorialSignals=request.checks.includes("style.patterns")?computeEditorialSignals(projection.text):undefined;
  const methods:MethodResult[]=[];for(const id of request.checks){const methodStarted=now();if(id.startsWith("unicode.")){methods.push(method(id,"unicode","Opace deterministic Unicode inspection",UNICODE_RULES_VERSION,unicode.length?"attention":"pass",unicode.map(x=>({type:"unicode_finding",...x})),limits("Unicode controls can be legitimate in multilingual text."),methodStarted,now(),"browser"));}else if(id==="style.patterns"){const signalsAttention=patternFindings.length>0||(editorialSignals?.status==="scored"&&editorialSignals.classification!=="human_like");const evidence:Record<string,unknown>[]=patternFindings.length?patternFindings.map(x=>({type:"pattern_finding",rule_id:x.rule_id,span:x.span})):[{type:"scope_note",rules_run:WRITING_SIGNAL_RULES_RUN,note:"No selected writing-signal rule matched. This is not evidence of human authorship."}];if(editorialSignals)evidence.push({type:"editorial_signals",...editorialSignals});methods.push(method(id,"pattern","Opace writing-signal rules",EN_SIGNALS_PATTERN_VERSION,signalsAttention?"attention":"pass",evidence,limits("Writing patterns are editorial prompts, not detector or watermark evidence."),methodStarted,now(),"browser"));}else if(id==="watermark.anthropic"){methods.push({...method(id,"watermark","Anthropic official text-watermark detector","unavailable-2026-08-26","unsupported",[],["No official detector call was available. Local style or public SynthID tests are not substitutes.","Not yet available in this release."],methodStarted,now(),"browser"),availability:"not_available",native_outcome:"not_available"});}else methods.push(method(id,"detector",id,"unsupported/1","unsupported",[],["This requested method is not implemented in the deterministic browser core.","Not yet available in this release."],methodStarted,now(),"browser"));}
  // 2026.08.8: the three-axis verdict. Character forensics used to be discarded
  // at verdict time, then (2026.08.7) briefly allowed to escalate the verdict to
  // ai_like, which was the opposite error: a hidden character proves text
  // MANIPULATION, not AI ORIGIN. verdict/combine.ts now publishes three readings
  // that are never merged — the AI probability (a trained model only, and no
  // model runs in this deterministic core), the text-integrity and provenance
  // findings, and the editorial suggestions. Protected spans are not an input.
  const watermarkOutcome:WatermarkOutcome=request.checks.includes("watermark.anthropic")?"not_available":"not_supported";
  const combinedVerdict=computeCombinedVerdict({signals:editorialSignals,unicodeFindings:unicode,text:request.source.content,watermark:{outcome:watermarkOutcome}});
  const combinedRaised=combinedVerdict.text_integrity.status!=="clean";
  const summary={pass:0,attention:0,fail:0,inconclusive:0,unsupported:0,not_configured:0,not_run:0,error:0};for(const item of methods)summary[item.status]++;
  progress("complete");const result:any={schema_version:"1.0",contract_version:"1.0.0",request_id:request.request_id,analysis_id:options.analysisId?.()??`analysis_${sourceHash.slice(7,23)}`,source:{content_hash:sourceHash,normalised_hash:prefixedSha256(projection.text.normalize("NFC")),content_type:request.source.content_type,language:request.source.language,word_count:(projection.text.trim().match(/\S+/g)??[]).length},protected_spans:protectedSpans,pattern_findings:patternFindings,methods,summary,combined_verdict:combinedVerdict,limitations:[...new Set(["Authorship cannot be proved from these checks.",...projection.limitations,...(combinedRaised?combinedVerdict.limitations:[])])],started_at:started,completed_at:now()};return deepFreeze(result) as AnalysisResult;
}
function method(id:string,category:MethodResult["category"],provider:string,version:string,status:MethodResult["status"],evidence:Record<string,unknown>[],limitations:string[],started_at:string,completed_at:string,privacy_route:MethodResult["privacy_route"]):MethodResult{if(!limitations.length)throw new Error("method_limitations_required");return {id,category,provider_or_method:provider,version,status,score:null,threshold:null,segments:[],evidence,limitations:limitations as [string,...string[]],started_at,completed_at,privacy_route};}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value as any))deepFreeze(child);}return value;}
function hasUnpairedSurrogate(value:string):boolean{for(let i=0;i<value.length;i++){const code=value.charCodeAt(i);if(code>=0xd800&&code<=0xdbff){const next=value.charCodeAt(i+1);if(!(next>=0xdc00&&next<=0xdfff))return true;i++;}else if(code>=0xdc00&&code<=0xdfff)return true;}return false;}
