import {ContentIntegrityClientError,errorKind} from "./errors.js";
import {validateErrorEnvelope} from "./validation.js";
export interface TransportOptions{origin:URL;token?:()=>string|Promise<string>;fetchImpl?:typeof fetch;timeoutMs:number;maxResponseBytes:number}
export async function readBounded(response:Response,maximum:number):Promise<Uint8Array>{
  const advertised=Number(response.headers.get("content-length"));if(Number.isFinite(advertised)&&advertised>maximum){await response.body?.cancel();throw new ContentIntegrityClientError("bad_request","response_too_large","The local service response exceeded the configured limit.",response.status);}
  if(!response.body)return new Uint8Array();const reader=response.body.getReader(),chunks:Uint8Array[]=[];let total=0;
  try{for(;;){const {done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>maximum){await reader.cancel();throw new ContentIntegrityClientError("bad_request","response_too_large","The local service response exceeded the configured limit.",response.status);}chunks.push(value);}}
  finally{reader.releaseLock();}
  const output=new Uint8Array(total);let offset=0;for(const chunk of chunks){output.set(chunk,offset);offset+=chunk.byteLength;}return output;
}
export async function requestJson<T>(options:TransportOptions,path:string,init:RequestInit={},signal?:AbortSignal):Promise<{status:number,data:T}>{
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort("timeout"),options.timeoutMs);const abort=()=>controller.abort(signal?.reason);signal?.addEventListener("abort",abort,{once:true});
  try{const headers=new Headers(init.headers);headers.set("accept","application/json");if(init.body!==undefined)headers.set("content-type","application/json");if(options.token){const token=await options.token();if(!token)throw new ContentIntegrityClientError("auth","permission_denied","A bearer token is required.");headers.set("authorization",`Bearer ${token}`);}
    const response=await(options.fetchImpl??fetch)(new URL(path,options.origin),{...init,headers,signal:controller.signal,redirect:"error"});const contentType=response.headers.get("content-type")?.split(";",1)[0]?.trim().toLowerCase();if(contentType!=="application/json"){await response.body?.cancel();throw new ContentIntegrityClientError("internal_error","malformed_response","The local service returned an invalid media type.",response.status);}const raw=await readBounded(response,options.maxResponseBytes);let data:any;try{data=raw.byteLength?JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(raw)):{};}catch{throw new ContentIntegrityClientError("internal_error","malformed_response","The local service returned an invalid response.",response.status);}if(!response.ok){validateErrorEnvelope(data);const code=data.error.code;throw new ContentIntegrityClientError(errorKind(code,response.status),code,"The local service rejected the request.",response.status);}return {status:response.status,data};
  }catch(error){if(error instanceof ContentIntegrityClientError)throw error;if(controller.signal.aborted){if(signal?.aborted)throw new ContentIntegrityClientError("cancelled","job_cancelled","The local request was cancelled.");throw new ContentIntegrityClientError("timeout","engine_unreachable","The local service did not respond before the timeout.");}throw new ContentIntegrityClientError("unavailable","engine_unreachable","The local service could not be reached.");}finally{clearTimeout(timer);signal?.removeEventListener("abort",abort);}
}
