import test from "node:test";import assert from "node:assert/strict";
import {inspect,inspectUnicode,listMethods,registerPatternPack} from "../../../packages/core/dist/index.js";
const request={schema_version:"1.0",contract_version:"1.0.0",request_id:"req_core0001",created_at:"2026-08-26T10:00:00Z",source:{content:"In today's rapidly evolving landscape, Opace quoted £1,250.\u200b",content_type:"plain_text",language:"en-GB"},checks:["unicode.invisible","style.patterns","watermark.anthropic","unknown.check"],privacy:{allowed_routes:["browser"],save_receipt:false,retain_content:false}};
test("inspection is deterministic, immutable, canonical and offline",async()=>{const prior=globalThis.fetch;globalThis.fetch=()=>{throw new Error("network_forbidden")};try{const phases=[];const result=await inspect(structuredClone(request),{now:()=>"2026-08-26T10:00:00Z",analysisId:()=>"analysis_core001",onProgress:p=>phases.push(p)});assert.deepEqual(phases,["validating","mapping_text","unicode_checks","protected_spans","writing_patterns","complete"]);assert.equal(result.methods.find(x=>x.id==="watermark.anthropic").status,"unsupported");assert.equal(result.methods.find(x=>x.id==="watermark.anthropic").score,null);assert.equal(result.summary.unsupported,2);assert.ok(result.protected_spans.some(x=>x.kind==="currency"));assert.ok(result.pattern_findings.length>0);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.methods));}finally{globalThis.fetch=prior;}});
test("legitimate scripts and joiners are not automatically labelled malicious",()=>{assert.equal(inspectUnicode("العربية עברית हिन्दी 👩‍💻 café").length,0);});
test("pattern pack registration rejects duplicates and is removable",()=>{const pack={id:"example.pack",version:"1.0.0",rules:["example.rule"],inspect:()=>[]};const unregister=registerPatternPack(pack);assert.throws(()=>registerPatternPack(pack),/duplicate/);unregister();assert.doesNotThrow(()=>{const remove=registerPatternPack(pack);remove();});});
test("method catalogue carries no authorship aggregate",()=>{const methods=listMethods();assert.ok(methods.some(x=>x.id==="watermark.anthropic"&&x.state==="unsupported"));assert.equal(JSON.stringify(methods).includes("aiProbability"),false);});
const one=(text,expect)=>{const findings=inspectUnicode(text);assert.equal(findings.length,1,`expected 1 finding for ${expect.code_point}, got ${JSON.stringify(findings.map(f=>f.code_point))}`);const f=findings[0];assert.equal(f.code_point,expect.code_point);assert.equal(f.severity,expect.severity);assert.equal(f.fix,expect.fix);assert.equal(f.span.start_utf16,2);assert.ok(f.matched_text_hash.startsWith("sha256:"));assert.ok(Array.isArray(f.limitations)&&f.limitations.length>0);return f;};
test("every carrier category is detected at the correct span and severity",()=>{
  const cases=[["­","U+00AD","low","remove"],["͏","U+034F","medium","remove"],["؜","U+061C","medium","review"],["܏","U+070F","medium","review"],["࢐","U+0890","medium","review"],["࣢","U+08E2","medium","review"],["᠎","U+180E","medium","remove"],["​","U+200B","medium","remove"],["‌","U+200C","medium","remove"],["‍","U+200D","medium","remove"],["‎","U+200E","medium","review"],["‏","U+200F","medium","review"],["‮","U+202E","medium","review"],["⁠","U+2060","medium","remove"],["⁣","U+2063","medium","remove"],["⁦","U+2066","medium","review"],["⁪","U+206A","medium","remove"],["﻿","U+FEFF","low","remove"],["￹","U+FFF9","medium","review"],["\u{110bd}","U+110BD","medium","review"],["\u{e0001}","U+E0001","high","remove"],["\u{e0041}","U+E0041","high","remove"],["️","U+FE0F","medium","remove"],["\u{e0100}","U+E0100","medium","review"],[" ","U+00A0","note","space"],[" ","U+1680","low","space"],[" ","U+2000","low","space"],[" ","U+2009","note","space"],[" ","U+200A","low","space"],[" ","U+202F","note","space"],[" ","U+205F","note","space"],["　","U+3000","note","space"],[" ","U+2028","low","review"],[" ","U+2029","low","review"],["�","U+FFFD","high","review"]];
  for(const [ch,code_point,severity,fix] of cases)one(`ab${ch}cd`,{code_point,severity,fix});
  assert.equal(inspectUnicode("ab\u{e0041}cd")[0].name,"TAG CHARACTER 'A'");assert.equal(inspectUnicode("ab️cd")[0].name,"VARIATION SELECTOR-16");assert.equal(inspectUnicode("ab‮cd")[0].name,"RIGHT-TO-LEFT OVERRIDE");});
test("legitimate joiner and variation-selector contexts are exempt or downgraded",()=>{
  assert.equal(inspectUnicode("👩‍💻").length,0,"emoji ZWJ sequence must not be flagged");
  assert.equal(inspectUnicode("❤️‍🔥").length,0,"VS16 plus ZWJ emoji sequence must not be flagged");
  assert.equal(inspectUnicode("می‌خواهم").length,0,"Persian ZWNJ must not be flagged");
  const vsAfterHan=inspectUnicode("葛\u{e0100}飾");assert.equal(vsAfterHan.length,1);assert.equal(vsAfterHan[0].severity,"note");
  const zwjLatin=inspectUnicode("ab‍cd");assert.equal(zwjLatin.length,1);assert.equal(zwjLatin[0].severity,"medium");});
test("French typographic spacing stays note severity only",()=>{const findings=inspectUnicode("Voulez-vous ? Il y a 10 000 mètres !");assert.equal(findings.length,3);for(const f of findings)assert.equal(f.severity,"note");});
test("homoglyph battery catches full Cyrillic and Greek confusable sets in mixed-script tokens",()=>{
  const battery=[["lіnk","U+0456"],["bloкchain","U+043A"],["passwοrd","U+03BF"],["pаypal","U+0430"],["mоney","U+043E"],["ѕcam","U+0455"],["јob","U+0458"],["ԁata","U+0501"],["Αpple","U+0391"],["Μicrosoft","U+039C"],["Тest","U+0422"],["cliνk","U+03BD"]];
  for(const [token,code_point] of battery){const findings=inspectUnicode(`safe ${token} safe`);assert.equal(findings.length,1,`expected 1 homoglyph finding for ${token}`);assert.equal(findings[0].code_point,code_point);assert.equal(findings[0].fix,"review");assert.match(findings[0].id,/homoglyph/);}});
test("pure Cyrillic and Greek words are never flagged as homoglyphs",()=>{assert.equal(inspectUnicode("привет мир Москва").length,0);assert.equal(inspectUnicode("καλημέρα κόσμε Ελλάδα").length,0);});
test("50,000-character document is inspected in under 200ms",async()=>{const {UNICODE_RULES_VERSION}=await import("../../../packages/core/dist/unicode/inspect.js");assert.match(UNICODE_RULES_VERSION,/^unicode:\d{4}\.\d{2}\.\d+$/);assert.notEqual(UNICODE_RULES_VERSION,"unicode:2026.08.1");
  const doc=("The quick brown fox jumps over the lazy dog. ".repeat(1110)+"​‌️\u{e0041} ").slice(0,50000);inspectUnicode(doc);const start=performance.now();const findings=inspectUnicode(doc);const elapsed=performance.now()-start;assert.ok(findings.length>0);assert.ok(elapsed<200,`unicode inspection took ${elapsed.toFixed(1)}ms`);});
