import test from "node:test";
import assert from "node:assert/strict";
import {spawnSync} from "node:child_process";
import {mkdtempSync,readFileSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {runCli} from "../dist/main.js";
const cli=new URL("../dist/main.js",import.meta.url);const run=(args,input="")=>spawnSync(process.execPath,[cli.pathname,...args],{input,encoding:"utf8",env:{...process.env,NO_COLOR:"1"}});

test("stdin and file inspection have equivalent stable output and clean JSON stdout",()=>{const dir=mkdtempSync(join(tmpdir(),"oaci-cli-")),file=join(dir,"input.txt"),text="Evidence\u200b costs £1,250.";writeFileSync(file,text);const a=run(["inspect","-","--checks","unicode,homoglyph,patterns,protected","--locale","en-GB","--format","json"],text),b=run(["inspect",file,"--format","json"]);assert.equal(a.status,0,a.stderr);assert.equal(b.status,0,b.stderr);const aa=JSON.parse(a.stdout),bb=JSON.parse(b.stdout);for(const value of [aa,bb]){delete value.started_at;delete value.completed_at;for(const method of value.methods){delete method.started_at;delete method.completed_at;}}bb.methods=bb.methods.filter(method=>method.id!=="watermark.anthropic");bb.summary.unsupported=0;assert.deepEqual(aa,bb);assert.equal(a.stderr,"");assert.equal(run(["inspect","-","--fail-on","attention"],text).status,4);});

test("HTML is self-contained and held commands have unavailable exits",()=>{const html=run(["inspect","-","--format","html"],"<script>bad()</script>Safe");assert.equal(html.status,0);assert.match(html.stdout,/<!doctype html>/);assert.doesNotMatch(html.stdout,/<script|https?:\/\//);assert.equal(run(["unknown"]).status,2);for(const args of [["serve"],["improve"],["benchmark"],["watermark","lab","list"]])assert.equal(run(args).status,3,args.join(" "));assert.equal(run(["--config","x","inspect","-"]).status,2);});

test("public runtime identity is version 0.1.0",()=>{assert.equal(run(["--version"]).stdout,"0.1.0\n");const text=run(["inspect","-"],"Evidence");assert.equal(text.status,0,text.stderr);assert.match(text.stdout,/Opace AI Content Integrity 0\.1\.0/);assert.doesNotMatch(text.stdout,/private/);const dir=mkdtempSync(join(tmpdir(),"oaci-version-")),receipt=join(dir,"receipt.json");assert.equal(run(["inspect","-","--receipt",receipt],"Evidence").status,0);assert.equal(JSON.parse(readFileSync(receipt,"utf8")).product_version,"0.1.0");});

test("hash-only redaction allowlists fields, rehashes and never overwrites",()=>{const dir=mkdtempSync(join(tmpdir(),"oaci-receipt-")),receipt=join(dir,"receipt.json"),hostile=join(dir,"hostile.json"),redacted=join(dir,"redacted.json");assert.equal(run(["--offline","inspect","-","--format","json","--receipt",receipt],"Private source £20").status,0);const value=JSON.parse(readFileSync(receipt,"utf8"));value.secret="TOP-LEVEL-SECRET";value.source.secret="SOURCE-SECRET";value.methods[0].evidence=[{secret:"EVIDENCE-SECRET"}];writeFileSync(hostile,JSON.stringify(value));const redact=run(["receipt","redact",hostile,"--format","json","--output",redacted]);assert.equal(redact.status,0,redact.stderr);const raw=readFileSync(redacted,"utf8"),safe=JSON.parse(raw);assert.doesNotMatch(raw,/SECRET/);assert.equal(safe.contains_content,false);assert.equal(safe.source.content,undefined);assert.equal(safe.integrity.signature,undefined);assert.match(safe.integrity.payload_hash,/^sha256:[a-f0-9]{64}$/);assert.equal(run(["receipt","verify",redacted,"--format","json"]).status,0);assert.equal(run(["receipt","redact",receipt,"--output",redacted]).status,2);});

test("bounded input and explicit gate policy",()=>{const dir=mkdtempSync(join(tmpdir(),"oaci-bound-")),large=join(dir,"large.txt"),source=join(dir,"source.txt"),candidate=join(dir,"candidate.txt");writeFileSync(large,"x".repeat(250001));writeFileSync(source,"Price £10.");writeFileSync(candidate,"Price changed.");assert.equal(run(["inspect",large]).status,2);assert.equal(run(["inspect","-"],"x".repeat(250001)).status,2);assert.equal(run(["compare",source,candidate]).status,0);assert.equal(run(["compare",source,candidate,"--fail-on-gate"]).status,4);const locks=join(dir,"locks.json");assert.equal(run(["protect","extract",source,"--format","json","--output",locks]).status,0);assert.equal(run(["protect","validate",source,candidate,"--locks",locks,"--fail-on","gate"]).status,4);});

test("quiet text mode is silent and offline inspection never calls fetch",async()=>{let calls=0;const original=globalThis.fetch;globalThis.fetch=async()=>{calls++;throw new Error("network_forbidden");};const stdout=[],stderr=[];try{const code=await runCli({argv:["--offline","--quiet","inspect","-"],stdin:(async function*(){yield new TextEncoder().encode("Offline evidence");})(),stdout:value=>stdout.push(value),stderr:value=>stderr.push(value),env:{NO_COLOR:"1"}});assert.equal(code,0);assert.deepEqual(stdout,[]);assert.deepEqual(stderr,[]);assert.equal(calls,0);}finally{globalThis.fetch=original;}});

test("receipt render rejects tampered or unvalidated input",()=>{const dir=mkdtempSync(join(tmpdir(),"oaci-render-")),receipt=join(dir,"receipt.json");assert.equal(run(["inspect","-","--receipt",receipt],"Evidence").status,0);const value=JSON.parse(readFileSync(receipt,"utf8"));value.source.content_hash="sha256:"+"f".repeat(64);writeFileSync(receipt,JSON.stringify(value));const rendered=run(["receipt","render",receipt]);assert.equal(rendered.status,2);assert.equal(rendered.stdout,"");assert.doesNotMatch(rendered.stderr,/Evidence|Traceback/);});

test("README quick-start commands are valid",()=>{const readme=readFileSync(new URL("../README.md",import.meta.url),"utf8");assert.match(readme,/opace-integrity protect extract article\.txt/);assert.match(readme,/opace-integrity receipt verify receipt\.json/);const dir=mkdtempSync(join(tmpdir(),"oaci-readme-")),article=join(dir,"article.txt"),locks=join(dir,"locks.json"),receipt=join(dir,"receipt.json");writeFileSync(article,"Opace evidence costs £10.");assert.equal(run(["protect","extract",article,"--output",locks]).status,0);assert.equal(run(["inspect",article,"--receipt",receipt]).status,0);assert.equal(run(["receipt","verify",receipt]).status,0);});
