"""Assemble the training/calibration corpus for the local-engine model tier.

Sources (each recorded with licence in manifest.json):
  Human side
    - wikitext-103-raw-v1 validation+test (2016 snapshot of Wikipedia Good/
      Featured articles; pre-2022 by construction). CC BY-SA 3.0.
    - HC3 human answers (finance / medicine / open_qa / wiki_csai; human text
      collected from pre-ChatGPT sources). CC BY-SA 4.0.
  AI side
    - HC3 ChatGPT answers (GPT-3.5, Dec 2022 era). CC BY-SA 4.0.
    - lmarena-ai/arena-human-preference-140k (Chatbot Arena battles, shard 0 spans
      2025-04..2025-07: Claude Opus 4, Grok 4, Gemini 2.5, DeepSeek-R1-0528,
      GPT-4.1-era OpenAI models and kin - the CURRENT-model slice). CC BY 4.0.
    - Locally generated GPT-2-small continuations (gpt2, MIT-style OpenAI
      licence) — generated by generate_gpt2.py into raw/gpt2-local.jsonl.

QUARANTINE: every candidate is checked against the eval set's 8-gram index and
the build aborts on any overlap (see quarantine.py). The eval file itself is
never copied into any output.

Output: corpus.jsonl (one doc per line) + manifest.json (provenance, licences,
counts, split assignment by sha256).
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import random
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "raw")
sys.path.insert(0, HERE)
from quarantine import Quarantine  # noqa: E402

MIN_WORDS, MAX_WORDS = 120, 700
TARGET_PER_SOURCE = {
    "wikitext103": 110,
    "hc3-human": 220,
    "hc3-chatgpt": 120,
    "arena-2024-25": 150,
    "gpt2-local": 60,
}
SEED = 20260828

URLS = {
    "hc3": ("https://huggingface.co/datasets/Hello-SimpleAI/HC3/resolve/main/all.jsonl", "hc3-all.jsonl"),
    "wikitext-val": (
        "https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/wikitext-103-raw-v1/validation-00000-of-00001.parquet",
        "wikitext103-validation.parquet",
    ),
    "wikitext-test": (
        "https://huggingface.co/datasets/Salesforce/wikitext/resolve/main/wikitext-103-raw-v1/test-00000-of-00001.parquet",
        "wikitext103-test.parquet",
    ),
    "arena": (
        "https://huggingface.co/datasets/lmarena-ai/arena-human-preference-140k/resolve/main/data/train-00000-of-00007.parquet",
        "arena140k-shard0.parquet",
    ),
}


def fetch(url: str, name: str) -> str:
    os.makedirs(RAW, exist_ok=True)
    path = os.path.join(RAW, name)
    if not os.path.exists(path):
        print(f"downloading {name} ...", flush=True)
        urllib.request.urlretrieve(url, path)
    return path


def wc(text: str) -> int:
    return len(text.split())


def looks_english_prose(text: str) -> bool:
    if not text:
        return False
    letters = sum(c.isalpha() for c in text)
    if letters / max(len(text), 1) < 0.6:
        return False
    ascii_frac = sum(ord(c) < 128 for c in text) / len(text)
    if ascii_frac < 0.95:
        return False
    if text.count("```") or text.count("    ") > 8:  # code-heavy
        return False
    return True


def clean_ws(text: str) -> str:
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def load_wikitext() -> list[dict]:
    import pandas as pd

    frames = [
        pd.read_parquet(fetch(*URLS["wikitext-val"])),
        pd.read_parquet(fetch(*URLS["wikitext-test"])),
    ]
    lines = [t for f in frames for t in f["text"].tolist()]
    docs, cur, title = [], [], None
    for ln in lines:
        m = re.match(r"^ = ([^=].*?) = $", ln.rstrip("\n"))
        if m:
            if title and cur:
                docs.append((title, "".join(cur)))
            title, cur = m.group(1), []
        elif title is not None and not ln.strip().startswith("="):
            cur.append(ln)
    if title and cur:
        docs.append((title, "".join(cur)))
    out = []
    for title, body in docs:
        body = re.sub(r" @(-|\.|,)@ ", r"\1", body)  # undo wikitext escaping
        body = clean_ws(body)
        # take the lead ~400 words at sentence boundary
        words = body.split()
        if len(words) < MIN_WORDS:
            continue
        text = " ".join(words[:450])
        text = text[: text.rfind(".") + 1] or text
        if wc(text) < MIN_WORDS:
            continue
        out.append(
            {
                "source": "wikitext103",
                "side": "human",
                "model": None,
                "genre": "wikipedia-article",
                "license": "CC BY-SA 3.0",
                "meta": {"title": title},
                "text": text,
            }
        )
    return out


def load_hc3() -> tuple[list[dict], list[dict]]:
    path = fetch(*URLS["hc3"])
    humans, ais = [], []
    with open(path) as f:
        for ln in f:
            row = json.loads(ln)
            src = row.get("source", "")
            if src == "reddit_eli5":
                continue  # casual register; keep the formal QA genres
            for ans in row.get("human_answers", []):
                humans.append(
                    {
                        "source": "hc3-human",
                        "side": "human",
                        "model": None,
                        "genre": f"qa-{src}",
                        "license": "CC BY-SA 4.0",
                        "meta": {"question": row.get("question", "")[:120]},
                        "text": clean_ws(ans),
                    }
                )
            for ans in row.get("chatgpt_answers", []):
                ais.append(
                    {
                        "source": "hc3-chatgpt",
                        "side": "ai",
                        "model": "gpt-3.5 (ChatGPT, 2022-12)",
                        "genre": f"qa-{src}",
                        "license": "CC BY-SA 4.0",
                        "meta": {"question": row.get("question", "")[:120]},
                        "text": clean_ws(ans),
                    }
                )
    return humans, ais


def load_arena() -> list[dict]:
    import pandas as pd

    import numpy as np

    df = pd.read_parquet(fetch(*URLS["arena"]))
    df = df[(df["language"] == "en") & (~df["is_code"].astype(bool))]
    out = []
    for _, row in df.iterrows():
        for side in ("a", "b"):
            model = row.get(f"model_{side}")
            conv = row.get(f"conversation_{side}")
            if conv is None or model is None:
                continue
            turns = list(conv) if isinstance(conv, (list, tuple, np.ndarray)) else []
            for t in turns:
                if isinstance(t, dict) and t.get("role") == "assistant":
                    content = t.get("content")
                    if isinstance(content, (list, tuple, np.ndarray)):
                        content = " ".join(
                            c.get("text") or "" for c in content if isinstance(c, dict)
                        )
                    if not isinstance(content, str):
                        continue
                    text = clean_ws(re.sub(r"^[#>\-\*\d\.\s]+", "", re.sub(r"[#*`_>|]", "", content), flags=re.M))
                    out.append(
                        {
                            "source": "arena-2024-25",
                            "side": "ai",
                            "model": str(model),
                            "genre": "chat-answer",
                            "license": "CC BY 4.0",
                            "meta": {},
                            "text": text,
                        }
                    )
                    break  # first assistant turn only
    return out


def load_gpt2_local() -> list[dict]:
    path = os.path.join(RAW, "gpt2-local.jsonl")
    if not os.path.exists(path):
        print("WARNING: raw/gpt2-local.jsonl missing — run generate_gpt2.py first")
        return []
    out = []
    with open(path) as f:
        for ln in f:
            row = json.loads(ln)
            row.update(
                source="gpt2-local",
                side="ai",
                model="gpt2 (124M, local MPS)",
                genre="continuation",
                license="Modified MIT (OpenAI gpt-2)",
            )
            row.setdefault("meta", {})
            out.append(row)
    return out


def main() -> None:
    rng = random.Random(SEED)
    q = Quarantine()
    print(f"quarantine index built from {q.n_eval} eval samples at {q.eval_path}")

    pools: dict[str, list[dict]] = {}
    wt = load_wikitext()
    hc3_h, hc3_a = load_hc3()
    pools["wikitext103"] = wt
    pools["hc3-human"] = hc3_h
    pools["hc3-chatgpt"] = hc3_a
    pools["arena-2024-25"] = load_arena()
    pools["gpt2-local"] = load_gpt2_local()

    corpus, seen = [], set()
    stats: dict[str, dict] = {}
    for source, pool in pools.items():
        eligible = []
        for d in pool:
            n = wc(d["text"])
            if not (MIN_WORDS <= n <= MAX_WORDS):
                continue
            if not looks_english_prose(d["text"]):
                continue
            h = hashlib.sha256(d["text"].encode()).hexdigest()
            if h in seen:
                continue
            seen.add(h)
            d["sha256"] = h
            d["words"] = n
            eligible.append(d)
        rng.shuffle(eligible)
        take = TARGET_PER_SOURCE.get(source, 0)
        if source == "arena-2024-25":
            # spread across models: round-robin per model family
            by_model: dict[str, list[dict]] = {}
            for d in eligible:
                by_model.setdefault(d["model"], []).append(d)
            picked, i = [], 0
            while len(picked) < take and any(by_model.values()):
                for m in list(by_model):
                    if by_model[m]:
                        picked.append(by_model[m].pop())
                        if len(picked) >= take:
                            break
                i += 1
            chosen = picked
        else:
            chosen = eligible[:take]
        # quarantine assertion on everything we keep (hard abort on violation)
        for d in chosen:
            q.assert_clean(d["text"], f"{source}:{d['sha256'][:12]}")
        stats[source] = {
            "pool": len(pool),
            "eligible": len(eligible),
            "kept": len(chosen),
        }
        corpus.extend(chosen)

    # deterministic split by hash: 60% train / 20% cal / 20% test-reserved
    for d in corpus:
        bucket = int(d["sha256"][:8], 16) % 10
        d["split"] = "train" if bucket < 6 else ("cal" if bucket < 8 else "test")
        d["id"] = f"{d['source']}-{d['sha256'][:12]}"

    out_path = os.path.join(HERE, "corpus.jsonl")
    with open(out_path, "w") as f:
        for d in corpus:
            f.write(json.dumps(d, ensure_ascii=False) + "\n")

    n_h = sum(d["side"] == "human" for d in corpus)
    n_a = sum(d["side"] == "ai" for d in corpus)
    manifest = {
        "built": "2026-08-28",
        "seed": SEED,
        "quarantine": {
            "eval_file": q.eval_path,
            "eval_samples": q.n_eval,
            "rule": "8-gram word-level containment, zero tolerance, build aborts on hit",
        },
        "filters": {"min_words": MIN_WORDS, "max_words": MAX_WORDS, "english_ascii": True},
        "sources": {
            "wikitext103": {
                "what": "wikitext-103-raw-v1 validation+test article leads (2016 Wikipedia snapshot, pre-2022 by construction)",
                "url": URLS["wikitext-val"][0],
                "license": "CC BY-SA 3.0",
            },
            "hc3-human": {
                "what": "HC3 human answers, formal QA genres (finance/medicine/open_qa/wiki_csai); human text predates ChatGPT",
                "url": URLS["hc3"][0],
                "license": "CC BY-SA 4.0",
            },
            "hc3-chatgpt": {
                "what": "HC3 ChatGPT answers (GPT-3.5, Dec 2022)",
                "url": URLS["hc3"][0],
                "license": "CC BY-SA 4.0",
            },
            "arena-2024-25": {
                "what": "lmarena-ai/arena-human-preference-140k shard 0 - first assistant turns from Chatbot Arena battles; shard 0 timestamps span 2025-04-17..2025-07-24 (53 distinct models incl. claude-opus-4, grok-4, gemini-2.5, deepseek-r1-0528)",
                "url": URLS["arena"][0],
                "license": "CC BY 4.0",
            },
            "gpt2-local": {
                "what": "GPT-2-small continuations generated locally (generate_gpt2.py, MPS)",
                "url": "local",
                "license": "Modified MIT (OpenAI gpt-2 weights)",
            },
        },
        "counts": {"human": n_h, "ai": n_a, "by_source": stats},
        "split": "sha256[:8] mod 10 -> 0-5 train, 6-7 cal, 8-9 test",
        "gaps": [
            "human-corpus-v1.json did not exist at build time (checked implementation/tests/battery/), so the planned half-for-training slice is absent",
            "arena-140k shard 0 covers models to 2025-07 (incl. claude-opus-4, grok-4, gemini-2.5, deepseek-r1); nothing newer than 2025-07 (no GPT-5.x-class 2026 outputs), so decay against 2026 frontier models is expected and must be measured, not assumed",
            "human side lacks professional marketing copy and personal-essay genres; wikipedia+QA only",
        ],
    }
    with open(os.path.join(HERE, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    print(json.dumps(manifest["counts"], indent=2))
    print(f"wrote {len(corpus)} docs -> {out_path}")


if __name__ == "__main__":
    main()
