import test from "node:test";
import assert from "node:assert/strict";
import {readFileSync,readdirSync} from "node:fs";
import {createAdminClient,createLocalClient,parseSse,validateLocalOrigin} from "../dist/index.js";
import {validateAnalysisRequest,validateAnalysisResult,validateCapabilities,validateCheckerResult,validateJob,validateReceiptRequest,validateRewriteRequest} from "../dist/validation.js";

const request={schema_version:"1.0",contract_version:"1.0.0",request_id:"req_test001",created_at:"2026-08-26T10:00:00Z",source:{content:"Test",content_type:"plain_text",language:"en-GB"},checks:[],privacy:{allowed_routes:["local_service"],save_receipt:false,retain_content:false}};
const rewrite={schema_version:"1.0",contract_version:"1.0.0",request_id:"req_test001",created_at:"2026-08-26T10:00:00Z",source:request.source,protected_spans:[],candidate_count:1,allowed_routes:["local_service"],checks:[],gate_policy:"strict"};
const receipt={schema_version:"1.0",contract_version:"1.0.0",product_version:"0",receipt_id:"receipt_test001",created_at:"2026-08-26T10:00:00Z",source:{content_hash:"sha256:"+"a".repeat(64),normalised_hash:"sha256:"+"a".repeat(64),content_type:"plain_text",language:"en-GB",word_count:1},policy:{id:"test",version:"1",requested_checks:[],allowed_routes:["local_service"],retain_content:false},methods:[],rewrite:null,approval:{scope:"none"},limitations:["test"],contains_content:false,integrity:{canonicalisation:"RFC8785",payload_hash:"sha256:"+"0".repeat(64)}};

test("construction is side-effect free and origin is exact",async()=>{let calls=0;const client=createLocalClient({fetchImpl:async()=>{calls++;return Response.json({status:"ok"})}});assert.equal(calls,0);assert.deepEqual(await client.health(),{status:"ok"});assert.equal(calls,1);for(const bad of ["http://localhost:8741","http://127.0.0.1:8741/v1","http://user@127.0.0.1:8741","http://127.1:8741","https://127.0.0.1:8741","http://127.0.0.1:0","http://127.0.0.1:65536","http://127.0.0.1:8741#x","http://127.0.0.1:8741?x=1"])assert.throws(()=>validateLocalOrigin(bad));});

test("invalid transport bounds fail before any I/O",()=>{let calls=0;const fetchImpl=async()=>{calls++;return Response.json({status:"ok"});};for(const options of [{timeoutMs:0},{timeoutMs:Infinity},{timeoutMs:300001},{maxResponseBytes:0},{maxResponseBytes:1.5},{maxResponseBytes:16000001}])assert.throws(()=>createLocalClient({...options,fetchImpl}));assert.equal(calls,0);});

test("all frozen operations use exact routes and scopes",async()=>{const seen=[];const fetchImpl=async(url,init={})=>{const path=new URL(url).pathname;seen.push([path,init.method??"GET",new Headers(init.headers).get("authorization")]);if(path==="/health")return Response.json({status:"ok"});if(path==="/v1/capabilities")return Response.json({schema_version:"1.0",product:"local",version:"0",contract_version:"1.0.0",schema_versions:["1.0"],limits:{max_request_bytes:250000,max_candidates:5,max_concurrent_jobs:1},methods:[]});if(path.endsWith("/events"))return new Response("data: {}\n\n",{headers:{"content-type":"text/event-stream"}});if(path.includes("receipts"))return Response.json({valid:true,schema_version:"1.0",contract_version:"1.0.0",errors:[]});if(path.includes("admin"))return Response.json({schema_version:"1.0",request_id:"req_test001",error:{code:"method_not_configured",message:"disabled",retryable:false}},{status:501});if((init.method??"GET")==="DELETE")return Response.json({status:path.endsWith("payload")?"deleted":"cancelled",request_id:"req_test001"});return Response.json({schema_version:"1.0",contract_version:"1.0.0",job_id:"job_test001",request_id:"req_test001",state:"failed",transitions:[],candidates:[],created_at:"2026-08-26T10:00:00Z",updated_at:"2026-08-26T10:00:00Z"},{status:202});};const client=createLocalClient({token:()=>"run-secret",fetchImpl});await client.health();await client.capabilities();await client.analyse(request);await client.startRewrite(rewrite,"idem-test001");await client.getJob("job_test001");const events=await client.jobEvents("job_test001");assert.equal(await events.text(),"data: {}\n\n");await client.cancel("job_test001");await client.deletePayload("job_test001");await client.validateReceipt(receipt);const admin=createAdminClient({token:()=>"admin-secret",fetchImpl});await assert.rejects(()=>admin.planModelInstall());await assert.rejects(()=>admin.installModel());await assert.rejects(()=>admin.deleteModel("model-1"));assert.deepEqual(seen.map(x=>x.slice(0,2)),[["/health","GET"],["/v1/capabilities","GET"],["/v1/analyses","POST"],["/v1/rewrite-jobs","POST"],["/v1/jobs/job_test001","GET"],["/v1/jobs/job_test001/events","GET"],["/v1/jobs/job_test001","DELETE"],["/v1/jobs/job_test001/payload","DELETE"],["/v1/receipts/validate","POST"],["/v1/admin/models/plan","POST"],["/v1/admin/models/install","POST"],["/v1/admin/models/model-1","DELETE"]]);assert.equal(seen[0][2],null);assert.equal(seen[1][2],"Bearer run-secret");assert.equal(seen[9][2],"Bearer admin-secret");});

test("SSE enforces auth, media type, limits and cancellation",async()=>{const noToken=createLocalClient({fetchImpl:async()=>new Response()});await assert.rejects(()=>noToken.jobEvents("job_test001"),error=>error.code==="permission_denied");const badType=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>new Response("{}",{headers:{"content-type":"application/json"}})});await assert.rejects(()=>badType.jobEvents("job_test001"),error=>error.code==="malformed_response");const large=createLocalClient({token:()=>"run-secret",maxResponseBytes:3,fetchImpl:async()=>new Response("data: {}\n\n",{headers:{"content-type":"text/event-stream"}})});const stream=await large.jobEvents("job_test001");await assert.rejects(()=>stream.text(),error=>error.code==="response_too_large");let sawAbort=false;const slow=createLocalClient({token:()=>"run-secret",timeoutMs:10,fetchImpl:async(_url,init)=>new Promise((_resolve,reject)=>{init.signal.addEventListener("abort",()=>{sawAbort=true;reject(new DOMException("aborted","AbortError"));});})});await assert.rejects(()=>slow.jobEvents("job_test001"),error=>error.kind==="timeout");assert.equal(sawAbort,true);});

test("SSE parser accepts LF and CRLF frames split across byte boundaries",async()=>{const source="data: {\"kind\":\"lf\"}\n\ndata: {\"kind\":\"crlf\",\"text\":\"£\"}\r\n\r\n",bytes=new TextEncoder().encode(source);const body=new ReadableStream({start(controller){for(const byte of bytes)controller.enqueue(Uint8Array.of(byte));controller.close();}}),values=[];for await(const value of parseSse(new Response(body),64))values.push(value);assert.deepEqual(values,[{kind:"lf"},{kind:"crlf",text:"£"}]);});

test("SSE parser caps each pending event without rejecting multiple small events in one chunk",async()=>{const source="data: {}\r\n\r\ndata: {}\n\n",values=[];for await(const value of parseSse(new Response(source),8))values.push(value);assert.deepEqual(values,[{},{}]);const bytes=new TextEncoder().encode("data: {\"long\":true}\r\n\r\n"),body=new ReadableStream({start(controller){controller.enqueue(bytes.slice(0,7));controller.enqueue(bytes.slice(7,13));controller.enqueue(bytes.slice(13));controller.close();}});await assert.rejects(async()=>{for await(const _value of parseSse(new Response(body),8)){}},/sse_event_too_large/);});

test("SSE non-success responses require bounded frozen JSON errors",async()=>{const envelope={schema_version:"1.0",request_id:"req_test001",error:{code:"rate_limited",message:"wait",retryable:true}};const valid=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>Response.json(envelope,{status:429})});await assert.rejects(()=>valid.jobEvents("job_test001"),error=>error.code==="rate_limited"&&error.kind==="rate_limited");for(const response of [new Response("<h1>owned</h1>",{status:500,headers:{"content-type":"text/html"}}),Response.json({...envelope,schema_version:"2.0"},{status:500}),new Response("{",{status:500,headers:{"content-type":"application/json"}}),Response.json({...envelope,error:{...envelope.error,code:"attacker_code"}},{status:500})]){const client=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>response});await assert.rejects(()=>client.jobEvents("job_test001"),error=>error.code==="malformed_response"&&error.kind==="internal_error"&&!error.message.includes("owned")&&!error.message.includes("attacker"));}});

test("JSON and SSE responses stop reading at the configured byte cap",async()=>{const makeBody=()=>{let pulls=0;const body=new ReadableStream({pull(controller){pulls++;controller.enqueue(new TextEncoder().encode("xxxx"));if(pulls===20)controller.close();}});return{body,get pulls(){return pulls;}};};const success=makeBody();const client=createLocalClient({token:()=>"run-secret",maxResponseBytes:5,fetchImpl:async()=>new Response(success.body,{headers:{"content-type":"application/json"}})});await assert.rejects(()=>client.capabilities(),error=>error.code==="response_too_large");assert.ok(success.pulls<20);const failed=makeBody();const sse=createLocalClient({token:()=>"run-secret",maxResponseBytes:5,fetchImpl:async()=>new Response(failed.body,{status:500,headers:{"content-type":"application/json"}})});await assert.rejects(()=>sse.jobEvents("job_test001"),error=>error.code==="response_too_large");assert.ok(failed.pulls<20);});

test("request preflight caps the exact serialised body, including additive metadata",async()=>{let called=false;const client=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>{called=true;return Response.json({});}});const oversized={...request,padding:"x".repeat(249990)};await assert.rejects(()=>client.analyse(oversized),error=>error.message==="request_too_large");assert.equal(called,false);});

test("frozen schema validation rejects nested invalid data, majors and statuses",async()=>{for(const payload of [{schema_version:"2.0",contract_version:"2.0.0",product:"x",version:"1",schema_versions:["2.0"],limits:{max_request_bytes:1,max_candidates:1,max_concurrent_jobs:1},methods:[]},{schema_version:"1.0",contract_version:"1.0.0",product:"x",version:"1",schema_versions:["1.0"],limits:{max_request_bytes:1,max_candidates:1,max_concurrent_jobs:1},methods:[{id:"x",category:"detector",version:"1",state:"invented"}]},{schema_version:"1.0",contract_version:"1.0.0",product:"x"}]){const client=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>Response.json(payload)});await assert.rejects(()=>client.capabilities(),error=>error.code==="malformed_response");}const client=createLocalClient({token:()=>"run-secret",fetchImpl:async()=>Response.json({})});await assert.rejects(()=>client.analyse({...request,privacy:{...request.privacy,allowed_routes:["invented"]}}),error=>error.code==="invalid_request");await assert.rejects(()=>client.startRewrite({...rewrite,protected_spans:[{id:"bad",kind:"email"}]},"idem-test001"),error=>error.code==="invalid_request");await assert.rejects(()=>client.validateReceipt({...receipt,contains_content:true}),error=>error.code==="invalid_request");});

test("frozen valid and invalid top-level fixtures follow reader policy",()=>{const functions={"analysis-request.schema.json":validateAnalysisRequest,"analysis-result.schema.json":validateAnalysisResult,"checker-result.schema.json":validateCheckerResult,"rewrite-request.schema.json":validateRewriteRequest,"job.schema.json":validateJob,"capabilities.schema.json":validateCapabilities,"integrity-receipt.schema.json":validateReceiptRequest};for(const kind of ["valid","invalid"]){const directory=new URL(`../../../fixtures/contracts/${kind}/`,import.meta.url);for(const name of readdirSync(directory)){const fixture=JSON.parse(readFileSync(new URL(name,directory),"utf8")),validate=functions[fixture.schema];if(!validate)continue;if(kind==="valid")assert.doesNotThrow(()=>validate(fixture.data),name);else assert.throws(()=>validate(fixture.data),name);}}});
