import process from "node:process";
import {realpathSync} from "node:fs";
import {writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import {createHash} from "node:crypto";
import canonicalize from "canonicalize";
import {assertCheckerResultInvariants,buildReceipt,diff,extractProtectedSpans,inspect,prefixedSha256,validateCandidate,verifyReceipt} from "@opace/content-integrity-core";
import {validateCheckerResult,validateLocalOrigin} from "@opace/content-integrity-client";
import {readInput} from "./input.js";
import {PRODUCT_VERSION,render,type OutputFormat} from "./output.js";
import {EXIT,exitFor} from "./policy.js";

type IO={argv:string[];stdin:AsyncIterable<Uint8Array>;stdout:(v:string)=>void;stderr:(v:string)=>void;env:Record<string,string|undefined>};
type FailOn="attention"|"fail"|"gate";
const usage=`Usage: opace-integrity <command> [options]\nCommands: inspect, protect extract, protect validate, compare, receipt verify, receipt redact, receipt render, serve, improve, watermark lab, benchmark\nOptions: --format text|json|jsonl|html --no-colour --quiet --offline --local-engine --engine-origin http://127.0.0.1:8741 --version --methods\n`;

function options(argv:string[]){let format:OutputFormat="text",quiet=false,noColour=false,offline=false,localEngine=false,engineOrigin="http://127.0.0.1:8741",receipt:string|undefined,output:string|undefined,config:string|undefined,cacheDir:string|undefined,checks:string|undefined,locale="en-GB",locks:string|undefined,failOn:FailOn|undefined;const args:string[]=[];for(let i=0;i<argv.length;i++){const a=argv[i]!;const next=()=>{const value=argv[++i];if(!value)throw new Error("invalid_argument");return value;};if(a==="--format"){format=next() as OutputFormat;if(!["text","json","jsonl","html"].includes(format))throw new Error("invalid_format");}else if(a==="--quiet")quiet=true;else if(a==="--no-colour")noColour=true;else if(a==="--offline")offline=true;else if(a==="--local-engine")localEngine=true;else if(a==="--engine-origin")engineOrigin=next();else if(a==="--receipt")receipt=next();else if(a==="--output")output=next();else if(a==="--config")config=next();else if(a==="--cache-dir")cacheDir=next();else if(a==="--checks")checks=next();else if(a==="--locale")locale=next();else if(a==="--locks")locks=next();else if(a==="--fail-on")failOn=next() as FailOn;else if(a==="--fail-on-gate")failOn="gate";else args.push(a);}if(config||cacheDir)throw new Error("invalid_argument_config_and_cache_not_implemented");if(offline&&localEngine)throw new Error("offline_flag_conflicts_with_local_engine");if(!localEngine&&engineOrigin!=="http://127.0.0.1:8741")throw new Error("engine_origin_requires_local_engine");if(locale!=="en-GB")throw new Error("invalid_locale");if(failOn&&!(["attention","fail","gate"] as string[]).includes(failOn))throw new Error("invalid_fail_on");return{format,quiet,noColour,offline,localEngine,engineOrigin,args,receipt,output,checks,locale,locks,failOn};}

async function fullCheckerResult(origin:string,token:string|undefined,request:unknown){
  if(!token||token.length<16)throw new Error("local_engine_token_unavailable");
  let base:URL;try{base=validateLocalOrigin(origin);}catch{throw new Error("invalid_local_origin");}
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10_000);
  try{
    const response=await fetch(new URL("/v1/checker-results",base),{method:"POST",redirect:"manual",signal:controller.signal,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",accept:"application/vnd.opace.checker-result+json;version=1"},body:JSON.stringify(request)});
    if(response.type==="opaqueredirect"||response.status>=300&&response.status<400)throw new Error("local_engine_redirect_refused");
    const declared=Number(response.headers.get("content-length")??0);if(declared>2_000_000)throw new Error("local_engine_response_too_large");
    const raw=await response.text();if(new TextEncoder().encode(raw).length>2_000_000)throw new Error("local_engine_response_too_large");
    let value:any;try{value=JSON.parse(raw);}catch{throw new Error("local_engine_invalid_json");}
    if(!response.ok)throw new Error(`local_engine_${value?.error?.code??response.status}`);
    const contentType=response.headers.get("content-type")?.toLowerCase().split(";",1)[0]?.trim()??"";
    if(contentType!=="application/json"&&contentType!=="application/vnd.opace.checker-result+json")throw new Error("local_engine_invalid_content_type");
    validateCheckerResult(value);assertCheckerResultInvariants(value);if(value.route?.kind!=="loopback_engine")throw new Error("local_engine_route_mismatch");return value;
  }finally{clearTimeout(timer);}
}

const writeExclusive=(path:string,value:string|Uint8Array)=>writeFile(path,value,{flag:"wx",mode:384});
const requestedChecks=(raw?:string)=>{if(!raw)return["unicode.invisible","unicode.homoglyph","style.patterns","watermark.anthropic"];const map:Record<string,string|undefined>={unicode:"unicode.invisible",homoglyph:"unicode.homoglyph",patterns:"style.patterns",protected:undefined};const output:string[]=[];for(const name of raw.split(",")){if(name==="provenance"||name==="local-detectors")throw new Error("method_not_configured");if(!(name in map))throw new Error("invalid_check");if(map[name])output.push(map[name]!);}return[...new Set(output)];};
const shouldFail=(failOn:FailOn|undefined,result:any)=>failOn==="attention"&&result.methods?.some((item:any)=>["attention","fail","error"].includes(item.status))||failOn==="fail"&&result.methods?.some((item:any)=>["fail","error"].includes(item.status))||failOn==="gate"&&result.gates?.some((item:any)=>item.hard&&item.status!=="pass");
const readLocks=async(raw:string|undefined,source:string)=>{if(!raw||raw==="auto")return extractProtectedSpans({content:source,content_hash:prefixedSha256(source)});if(raw==="none")throw new Error("invalid_locks_none_requires_held_confirmation");const empty=(async function*(){})();const value=JSON.parse(await readInput(raw,empty));const spans=Array.isArray(value)?value:value.protected_spans;if(!Array.isArray(spans))throw new Error("invalid_locks");return spans;};

function redactedReceipt(receipt:any){const safe:any={schema_version:receipt.schema_version,contract_version:receipt.contract_version,product_version:receipt.product_version,receipt_id:receipt.receipt_id,created_at:receipt.created_at,source:{content_hash:receipt.source?.content_hash,normalised_hash:receipt.source?.normalised_hash,content_type:receipt.source?.content_type,language:receipt.source?.language,word_count:receipt.source?.word_count},policy:{id:receipt.policy?.id,version:receipt.policy?.version,requested_checks:Array.isArray(receipt.policy?.requested_checks)?receipt.policy.requested_checks:[],allowed_routes:Array.isArray(receipt.policy?.allowed_routes)?receipt.policy.allowed_routes:[],retain_content:false},methods:Array.isArray(receipt.methods)?receipt.methods.map((item:any)=>({id:item.id,category:item.category,provider_or_method:item.provider_or_method,version:item.version,status:item.status,...(item.availability?{availability:item.availability}:{}),...(item.native_outcome?{native_outcome:item.native_outcome}:{}),score:item.score,score_scale:item.score_scale??null,threshold:item.threshold,segments:[],evidence:[],limitations:["Evidence payload omitted during hash-only redaction."],started_at:item.started_at,completed_at:item.completed_at,privacy_route:item.privacy_route})):[],rewrite:receipt.rewrite?{source_hash:receipt.rewrite.source_hash,candidate_hash:receipt.rewrite.candidate_hash,generator:{route:receipt.rewrite.generator?.route,provider:receipt.rewrite.generator?.provider,model:receipt.rewrite.generator?.model,prompt_template:"[redacted]",parameters:{}},gates:Array.isArray(receipt.rewrite.gates)?receipt.rewrite.gates.map((gate:any)=>({id:gate.id,version:gate.version,status:gate.status,hard:gate.hard,summary:"Evidence omitted during hash-only redaction.",failures:[],limitations:[]})):[],selected_candidate:receipt.rewrite.selected_candidate}:null,approval:{scope:receipt.approval?.scope},limitations:["Content and free-form evidence omitted during hash-only redaction."],contains_content:false,integrity:{canonicalisation:"RFC8785"}};const encoded=canonicalize(safe);if(encoded===undefined)throw new Error("invalid_canonical_json");safe.integrity.payload_hash=`sha256:${createHash("sha256").update(encoded).digest("hex")}`;const checked=verifyReceipt(safe);if(!checked.valid)throw new Error(`invalid_redacted_receipt:${checked.errors.join(",")}`);return safe;}

export async function runCli(io:IO):Promise<number>{try{const parsed=options(io.argv);const [command,...args]=parsed.args;const emit=(value:string)=>{if(!parsed.quiet||parsed.format!=="text")io.stdout(value);};if(!command||command==="--help"){io.stdout(usage);return EXIT.ok;}if(command==="--version"){io.stdout(`${PRODUCT_VERSION}\n`);return EXIT.ok;}if(command==="--methods"){io.stdout("unicode.invisible\nunicode.homoglyph\nstyle.patterns\nwatermark.anthropic (unsupported)\n");return EXIT.ok;}if(command==="serve")throw new Error("service_not_configured_use_python_candidate");if(command==="improve"||command==="benchmark"||command==="watermark")throw new Error(command==="watermark"?"method_unsupported_watermark_lab_held":"method_not_configured");
    if(command==="inspect"){const path=args[0]??"-",content=await readInput(path,io.stdin),createdAt=new Date().toISOString(),hash=prefixedSha256(content),checks=requestedChecks(parsed.checks);const route=parsed.localEngine?"local_service":"browser";const request:any={schema_version:"1.0",contract_version:"1.0.0",request_id:`req_${hash.slice(7,23)}`,created_at:createdAt,source:{content,content_type:path.endsWith(".html")?"html":path.endsWith(".md")?"markdown":"plain_text",language:parsed.locale},checks,privacy:{allowed_routes:[route],save_receipt:Boolean(parsed.receipt),retain_content:false}};const result=parsed.localEngine?await fullCheckerResult(parsed.engineOrigin,io.env.OACI_RUN_TOKEN,request):await inspect(request,{now:()=>createdAt,analysisId:()=>`analysis_${hash.slice(7,23)}`});if(parsed.receipt){if(parsed.localEngine)throw new Error("checker_receipt_export_not_implemented");const receipt=await buildReceipt({receipt_id:`receipt_${hash.slice(7,23)}`,product_version:PRODUCT_VERSION,created_at:createdAt,source:request.source,policy:{id:"cli-offline",version:"1.0.0",requested_checks:request.checks,allowed_routes:["browser"],retain_content:false},methods:result.methods,rewrite:null,approval:{scope:"none"},limitations:result.limitations,contains_content:false});await writeExclusive(parsed.receipt,render(receipt,"json"));}emit(render(result,parsed.format,parsed.noColour||Boolean(io.env.NO_COLOR)));return shouldFail(parsed.failOn,result)?EXIT.gate:EXIT.ok;}
    if(command==="protect"){const action=args[0];if(action==="extract"){const content=await readInput(args[1]??"-",io.stdin),spans=extractProtectedSpans({content,content_hash:prefixedSha256(content)}),result={schema_version:"1.0",contract_version:"1.0.0",protected_spans:spans};const output=render(result,parsed.format);if(parsed.output)await writeExclusive(parsed.output,output);else emit(output);return EXIT.ok;}if(action==="validate"){if(!args[1]||!args[2])throw new Error("invalid_argument");const source=await readInput(args[1],io.stdin),candidate=await readInput(args[2],io.stdin),spans=await readLocks(parsed.locks,source),gates=validateCandidate({content:source,content_hash:prefixedSha256(source)},candidate,spans,{mode:"strict"}),result={schema_version:"1.0",contract_version:"1.0.0",gates};emit(render(result,parsed.format));return shouldFail(parsed.failOn,result)?EXIT.gate:EXIT.ok;}throw new Error("invalid_protect_action");}
    if(command==="compare"){if(!args[0]||args.length<2||args.length>6)throw new Error("invalid_argument");const source=await readInput(args[0],io.stdin),spans=await readLocks(parsed.locks,source),candidates=[];for(const path of args.slice(1)){const candidate=await readInput(path,io.stdin),gates=validateCandidate({content:source,content_hash:prefixedSha256(source)},candidate,spans,{mode:"strict"});candidates.push({path,source_hash:prefixedSha256(source),candidate_hash:prefixedSha256(candidate),diff:diff(source,candidate),gates});}const value={schema_version:"1.0",contract_version:"1.0.0",candidates};emit(render(value,parsed.format));return parsed.failOn==="gate"&&candidates.some(item=>shouldFail("gate",item))?EXIT.gate:EXIT.ok;}
    if(command==="receipt"){const action=args[0];if(!args[1])throw new Error("invalid_argument");const raw=await readInput(args[1],io.stdin),receipt=JSON.parse(raw);if(action==="verify"){const checked=verifyReceipt(receipt);emit(render({valid:checked.valid,schema_version:receipt.schema_version,contract_version:receipt.contract_version,errors:checked.errors.map((code:string)=>({code}))},parsed.format));return checked.valid?EXIT.ok:EXIT.invalid;}if(action==="redact"){const value=render(redactedReceipt(receipt),parsed.format);if(parsed.output)await writeExclusive(parsed.output,value);else emit(value);return EXIT.ok;}if(action==="render"){const checked=verifyReceipt(receipt);if(!checked.valid)throw new Error(`invalid_receipt:${checked.errors.join(",")}`);emit(render(receipt,"html"));return EXIT.ok;}throw new Error("invalid_receipt_action");}
    throw new Error("invalid_command");}catch(error){io.stderr(`${error instanceof Error?error.message:"internal_error"}\n`);return exitFor(error);}}

if(process.argv[1]&&realpathSync(process.argv[1])===fileURLToPath(import.meta.url)){const code=await runCli({argv:process.argv.slice(2),stdin:process.stdin,stdout:value=>process.stdout.write(value),stderr:value=>process.stderr.write(value),env:process.env});process.exitCode=code;}
