import { prefixedSha256 } from "../source/utf8.js";
export interface DiffSegment {type:"equal"|"insert"|"delete";text:string;source_start:number;source_end:number;candidate_start:number;candidate_end:number}
export interface ContentDiff {version:"lcs-token/1.0.0";source_hash:string;candidate_hash:string;change_count:number;segments:DiffSegment[];fallback:boolean}
const tokens=(s:string)=>s.match(/\s+|[^\s]+/g)??[];
export function diff(source:string,candidate:string):ContentDiff{
  if(source.length+candidate.length>80_000)return lineDiff(source,candidate);
  const a=tokens(source),b=tokens(candidate);if(a.length*b.length>2_000_000)return lineDiff(source,candidate);
  const matches=hirschberg(a,b);let i=0,j=0,sp=0,cp=0,mi=0;const out:DiffSegment[]=[];const push=(type:DiffSegment["type"],text:string,ss:number,se:number,cs:number,ce:number)=>{const last=out.at(-1);if(last?.type===type&&last.source_end===ss&&last.candidate_end===cs){last.text+=text;last.source_end=se;last.candidate_end=ce;}else out.push({type,text,source_start:ss,source_end:se,candidate_start:cs,candidate_end:ce});};
  while(i<a.length||j<b.length){const match=matches[mi];if(match&&i===match[0]&&j===match[1]){const t=a[i]!;push("equal",t,sp,sp+t.length,cp,cp+t.length);sp+=t.length;cp+=t.length;i++;j++;mi++;}else if(j<b.length&&(!match||j<match[1])){const t=b[j]!;push("insert",t,sp,sp,cp,cp+t.length);cp+=t.length;j++;}else{const t=a[i]!;push("delete",t,sp,sp+t.length,cp,cp);sp+=t.length;i++;}}
  return {version:"lcs-token/1.0.0",source_hash:prefixedSha256(source),candidate_hash:prefixedSha256(candidate),change_count:out.filter(x=>x.type!=="equal").length,segments:out,fallback:false};
}
function rowScores(a:string[],a0:number,a1:number,b:string[],b0:number,b1:number,reverse=false):Uint32Array{const width=b1-b0;let previous=new Uint32Array(width+1),current=new Uint32Array(width+1);for(let ai=0;ai<a1-a0;ai++){const av=a[reverse?a1-1-ai:a0+ai]!;for(let bj=0;bj<width;bj++){const bv=b[reverse?b1-1-bj:b0+bj]!;current[bj+1]=av===bv?previous[bj]!+1:Math.max(previous[bj+1]!,current[bj]!);}const swap=previous;previous=current;current=swap;current.fill(0);}return previous;}
function hirschberg(a:string[],b:string[]):Array<[number,number]>{const out:Array<[number,number]>=[];const walk=(a0:number,a1:number,b0:number,b1:number)=>{if(a0>=a1||b0>=b1)return;if(a1-a0===1){for(let j=b0;j<b1;j++)if(a[a0]===b[j]){out.push([a0,j]);break;}return;}const mid=(a0+a1)>>1;let left:Uint32Array|undefined=rowScores(a,a0,mid,b,b0,b1),right:Uint32Array|undefined=rowScores(a,mid,a1,b,b0,b1,true);let split=0,best=-1;for(let j=0;j<=b1-b0;j++){const score=left[j]!+right[b1-b0-j]!;if(score>best){best=score;split=j;}}left=undefined;right=undefined;walk(a0,mid,b0,b0+split);walk(mid,a1,b0+split,b1);};walk(0,a.length,0,b.length);return out;}
function lineDiff(source:string,candidate:string):ContentDiff{const segments:DiffSegment[]=source===candidate?(source?[{type:"equal",text:source,source_start:0,source_end:source.length,candidate_start:0,candidate_end:candidate.length}]:[]):[];if(source!==candidate){if(source)segments.push({type:"delete",text:source,source_start:0,source_end:source.length,candidate_start:0,candidate_end:0});if(candidate)segments.push({type:"insert",text:candidate,source_start:source.length,source_end:source.length,candidate_start:0,candidate_end:candidate.length});}return {version:"lcs-token/1.0.0",source_hash:prefixedSha256(source),candidate_hash:prefixedSha256(candidate),change_count:segments.filter(item=>item.type!=="equal").length,segments,fallback:true};}
