import canonicalize from "canonicalize";
import type { IntegrityReceipt, MethodResult, GateResult } from "@opacedev/ai-content-checker-contracts";
import { prefixedSha256 } from "../source/utf8.js";

export interface ReceiptInput {receipt_id:string;product_version:string;created_at:string;source:{content:string;content_type:"plain_text"|"html"|"markdown";language:string;normalised_text?:string};policy:{id:string;version:string;requested_checks:string[];allowed_routes:Array<"browser"|"wordpress_local"|"local_service"|"hub_provider"|"commercial_byok">;retain_content:boolean};methods:MethodResult[];rewrite?:{source_hash:string;candidate_hash:string;generator:{route:"browser"|"wordpress_local"|"local_service"|"hub_provider"|"commercial_byok";provider:string;model:string;prompt_template:string;parameters?:Record<string,unknown>};gates:GateResult[];selected_candidate:string|null;candidate_content?:string}|null;approval:{actor_id?:string;at?:string;scope:"whole"|"sentences"|"none";sentence_ids?:string[]};limitations:string[];contains_content:boolean}

const payloadForHash=(receipt:Record<string,unknown>)=>{const clone=structuredClone(receipt) as Record<string,any>;delete clone.integrity?.payload_hash;delete clone.integrity?.signature;return clone;};
const canonical=(value:unknown)=>{const output=canonicalize(value);if(output===undefined)throw new Error("receipt_canonicalisation_failed");return output;};
export async function buildReceipt(input:ReceiptInput):Promise<IntegrityReceipt>{
  if(input.contains_content!==input.policy.retain_content)throw new Error("receipt_content_consent_mismatch");
  if(input.contains_content&&input.rewrite&&!input.rewrite.candidate_content)throw new Error("receipt_candidate_content_required");
  const sourceHash=prefixedSha256(input.source.content),normalisedHash=prefixedSha256(input.source.normalised_text??input.source.content);
  const source:Record<string,unknown>={content_hash:sourceHash,normalised_hash:normalisedHash,content_type:input.source.content_type,language:input.source.language,word_count:(input.source.content.trim().match(/\S+/g)??[]).length};if(input.contains_content)source.content=input.source.content;
  const rewrite=input.rewrite?(()=>{const {candidate_content,source_content:_callerSourceContent,...metadata}=input.rewrite as ReceiptInput["rewrite"]&{source_content?:string};return {...metadata,...(input.contains_content?{source_content:input.source.content,candidate_content}:{} )};})():null;
  const receipt:any={schema_version:"1.0",contract_version:"1.0.0",product_version:input.product_version,receipt_id:input.receipt_id,created_at:input.created_at,source,policy:input.policy,methods:input.methods,rewrite,approval:input.approval,limitations:input.limitations,contains_content:input.contains_content,integrity:{canonicalisation:"RFC8785",payload_hash:"sha256:"+"0".repeat(64)}};
  receipt.integrity.payload_hash=prefixedSha256(canonical(payloadForHash(receipt)));
  return deepFreeze(receipt) as IntegrityReceipt;
}
export function verifyReceipt(receipt:IntegrityReceipt):{valid:boolean;errors:string[];payload_hash:string}{const errors=validateReceiptShape(receipt as any);let expected="";try{expected=prefixedSha256(canonical(payloadForHash(receipt as any)));if(expected!==receipt?.integrity?.payload_hash)errors.push("payload_hash_mismatch");}catch{errors.push("receipt_canonicalisation_failed");}return {valid:errors.length===0,errors:[...new Set(errors)],payload_hash:expected};}
const isHash=(value:unknown)=>typeof value==="string"&&/^sha256:[a-f0-9]{64}$/.test(value);
const isTime=(value:unknown)=>typeof value==="string"&&!Number.isNaN(Date.parse(value));
function validateReceiptShape(receipt:any):string[]{const e:string[]=[];if(!receipt||typeof receipt!=="object")return ["invalid_receipt"];if(receipt.schema_version!=="1.0")e.push("unsupported_schema");if(typeof receipt.contract_version!=="string"||!receipt.contract_version.startsWith("1."))e.push("contract_incompatible");for(const key of ["product_version","receipt_id"])if(typeof receipt[key]!=="string"||!receipt[key])e.push(`missing_${key}`);if(!isTime(receipt.created_at))e.push("invalid_created_at");if(!receipt.source||!isHash(receipt.source.content_hash)||!isHash(receipt.source.normalised_hash)||!Number.isInteger(receipt.source.word_count)||receipt.source.word_count<0||!["plain_text","html","markdown"].includes(receipt.source.content_type)||typeof receipt.source.language!=="string")e.push("invalid_source");if(!receipt.policy||typeof receipt.policy.retain_content!=="boolean"||!Array.isArray(receipt.policy.requested_checks)||!Array.isArray(receipt.policy.allowed_routes))e.push("invalid_policy");if(typeof receipt.contains_content!=="boolean")e.push("invalid_contains_content");if(receipt.policy&&receipt.contains_content!==receipt.policy.retain_content)e.push("receipt_content_consent_mismatch");if(receipt.source&&receipt.contains_content!==Object.hasOwn(receipt.source,"content"))e.push("receipt_content_flag_mismatch");if(receipt.rewrite){if(!isHash(receipt.rewrite.source_hash)||!isHash(receipt.rewrite.candidate_hash)||!receipt.rewrite.generator||!Array.isArray(receipt.rewrite.gates)||!(typeof receipt.rewrite.selected_candidate==="string"||receipt.rewrite.selected_candidate===null))e.push("invalid_rewrite");const hasSource=Object.hasOwn(receipt.rewrite,"source_content"),hasCandidate=Object.hasOwn(receipt.rewrite,"candidate_content");if(receipt.contains_content?(!hasSource||!hasCandidate):(hasSource||hasCandidate))e.push("rewrite_content_flag_mismatch");}if(!Array.isArray(receipt.methods))e.push("invalid_methods");else for(const method of receipt.methods){if(!method||typeof method.id!=="string"||typeof method.version!=="string"||!["pass","attention","fail","inconclusive","unsupported","not_configured","not_run","error"].includes(method.status)||!isTime(method.started_at)||!isTime(method.completed_at)||!Array.isArray(method.limitations)||!method.limitations.length)e.push("invalid_method");}if(!receipt.approval||!["whole","sentences","none"].includes(receipt.approval.scope))e.push("invalid_approval");if(!Array.isArray(receipt.limitations)||!receipt.limitations.length)e.push("invalid_limitations");if(receipt.integrity?.canonicalisation!=="RFC8785"||!isHash(receipt.integrity?.payload_hash))e.push("invalid_integrity");return e;}
function deepFreeze<T>(value:T):T{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value as any))deepFreeze(child);}return value;}
